appd_user: appd
appd_group: appd
appd_install_directory: /opt/appdynamics
appd_tmp_directory: "{{ appd_install_directory }}/tmp"

required_packages:
  - curl
  - ncurses
  - net-tools
  - fontconfig
  - libaio
  - numactl

